spring:
  datasource:
    url: jdbc:mysql://us-cdbr-iron-east-01.cleardb.net/heroku_4cc5f4d6131b075?reconnect=true&characterEncoding=utf8&useUnicode=true
    username: bc91784b965748
    password: 80fd2b5f
    driver-class-name: com.mysql.jdbc.Driver
    tomcat:
      test-while-idle: true
      validation-query: SELECT 1
    initialization-mode: never
    platform: mysql
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: validate

check-user-scopes: true